### PR TITLE
Fixes issue with versionstamp in update-function. Partially fixes #5.

### LINKED ISSUE #5: Enforce schemas for `create` & `update` operations

### PR DESCRIPTION
**Pull request by jnssnmrcs**
The current update function never received the versionstamp, issue was hidden because of typescript cast.

### CODE REVIEW

**Comment by jnssnmrcs** [comment]
I just realized there were no tests for updateMany function and it does not seem to be working at all, need to look a bit more into it.

**Comment by skoshx** [comment]
@jnssnmrcs Whatever feels easiest to you! I will try to review these by Friday, have been super busy unfortunately!

**Comment by jnssnmrcs** [comment]
It should be fixed now.

**Comment by skoshx** [comment]
Thanks a lot for the fixes, good quality clean-up and adding the tests!! I don't know what I was thinking when I was writing the `chainSet` etc :D

**Pull request merged**
