### PR TITLE
type fixes, refactor pentagon.ts

### PR DESCRIPTION
**Pull request by lilnasy**
- Commented out the methods that have not yet been implemented.
- The methods return promises, the types now reflect that.
- Refactored pentagon to provide type annotations at multiple places. This will help you know which part of the implementation doesn't align with the interface.
- Went overboard with the types, feel free to dial it back.

### CODE REVIEW

**Comment by skoshx** [comment]
Nice, thank you for your contribution! I think everything looks great, every `@ts-ignore` and `@ts-expect-error` that can be removed is good :D Is the code formatted with `deno fmt` btw?

**Comment by lilnasy** [comment]
@skoshx I haven't, it's unformatted.

**Comment by lilnasy** [comment]
Done.

**Comment by skoshx** [comment]
Thanks a lot!

**Pull request merged**
