### PR TITLE
Update zod to the latest non-vulnerable version

### PR DESCRIPTION
**Pull request by waptik**
see https://github.com/colinhacks/zod/pull/2824

### CODE REVIEW

**Comment by skoshx** [comment]
Yikes, quite a bad vulnerability, thanks a lot for this!

**Comment by waptik** [comment]
You're welcome but a new version hasn't been published on deno x yet

**Comment by skoshx** [comment]
Hello, yeah, sorry about that, haven't really had time for any personal todo list tasks the last week as I've been sick!

Just released v0.1.5! :)

**Comment by waptik** [comment]
Sorry about your health. Thanks for the release but it looks like just
updating zod’s version brings up some type issues as seen in the screenshot
below. This makes response hint weird type definitions

**Pull request merged**
